version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200"  # REST API için
      - "9300:9300"  # Transport için
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false  # Güvenlik devre dışı
      - xpack.monitoring.enabled=false  # Monitoring devre dışı
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true  # Bellek kilitleme (performans için)
    ulimits:
      memlock:
        soft: -1
        hard: -1  # Bellek kilit limitlerini kaldır
    networks:
      - elk


  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"  # Kibana arayüzü için
    volumes:
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk
    depends_on:
      - elasticsearch

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    ports:
      - "2020:2020"  # Metrics endpoint (isteğe bağlı)
    volumes:
      - ./fluent-bit-config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf  # Fluent Bit yapılandırma dosyası
      - ./logs:/logs  # Log dosyalarını bind etmek için
    environment:
      - FLB_LOG_LEVEL=info  # Log seviyesi
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elastic_data:
    driver: local
  logstash_data:
    driver: local
  kibana_data:
    driver: local
